services:
  postgres:
    image: postgres:15-alpine
    container_name: delayed-notifier-db
    restart: unless-stopped
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./postgresql-config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: qqq
      POSTGRES_DB: test
      POSGTRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  app:
    build:
      context: ../app
      dockerfile: ../app/dockerfile.production
    ports:
      - "80:8080"
    environment:
      - DEBUG=false
      - PORT=8080
      - POSTGRES_CONN=postgresql://dev:qqq@postgres:5432/test?sslmode=disable
      - CONFIG_PATH=../config/config.yml
      - TEMPLATES=templates/*.html
    volumes:
      - ../config:/config
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
    driver: local
